version: "3.7"
services:
  onizuka:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: docker.pkg.github.com/lcse/onizuka/onizuka
    container_name: onizuka
    restart: always
    tty: true
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    working_dir: /opt/${APP_NAME}
    volumes:
      - .:/opt/${APP_NAME}:rw
      - node_modules:/opt/${APP_NAME}/node_modules
    depends_on:
      - postgres
    entrypoint: /bin/sh
    # command: ["yarn", "start:dev"]
    command: -c "yarn --frozen-lockfile --ignore-optional --no-progress --silent --force && yarn start:dev"
    networks:
      - onizukanet
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: onizuka
      POSTGRES_USER: onizuka
      POSTGRES_PASSWORD: onizuka
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - onizukanet
volumes:
  node_modules:
  postgres:
networks:
  onizukanet:
    external: true
